apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: tex-dev
  name: tex-dev-claim
  labels:
    app: tex-dev-app
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: openebs-hostpath
  resources:
    requests:
      storage: 10Gi